#!/usr/bin/env node
/**
 * Generates app/compat/compat.generated.ts — the compatibility matrix, wrapped
 * as a TypeScript module the /compat route imports.
 *
 * Why a generated module and not public/compat/index.html: Next serves public/
 * by exact path and does no directory-index resolution, so the file is only
 * reachable at /compat/index.html — /compat itself 404s. A rewrite could
 * plausibly bridge that, but it would make the page's URL depend on rewrite
 * ordering semantics that differ between Next versions. A route owns its URL
 * outright and is verified by smoke.spec.ts, so there is nothing to get wrong.
 *
 * The HTML is embedded with JSON.stringify rather than a template literal: it
 * is 57 kB of arbitrary markup containing backticks and `${`, either of which
 * would silently corrupt or break a template literal. JSON.stringify emits a
 * fully-escaped JS string literal for any input.
 *
 * Deliberately tolerant of failure. A marketing site that will not build
 * because a supplementary page could not render is a worse outcome than a site
 * missing that page — the route falls back to a short placeholder, everything
 * else ships, and the log says why. The canonical copy lives in the repo either
 * way, and packages/website/tests/smoke.spec.ts fails if /compat stops carrying
 * real recorded runs.
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const WEBSITE = join(HERE, "..");
const REPO_ROOT = join(WEBSITE, "..", "..");
const RENDERER = join(REPO_ROOT, "contract", "render-compat.mjs");
const SCRATCH = join(WEBSITE, ".generated", "compat.html");
const MODULE = join(WEBSITE, "app", "compat", "compat.generated.ts");

const PLACEHOLDER =
  "<!doctype html><meta charset=utf-8><title>Compatibility</title>" +
  "<p>The compatibility matrix could not be generated for this build. " +
  '<a href="https://github.com/SammyTourani/evestack/tree/main/contract/history">' +
  "The recorded reports it is built from are in the repository.</a>";

function emit(html) {
  mkdirSync(dirname(MODULE), { recursive: true });
  writeFileSync(
    MODULE,
    "// Generated by scripts/render-compat.mjs on prebuild. Do not edit.\n" +
      "// Source of truth: contract/history/*.json via contract/render-compat.mjs.\n" +
      `export const compatHtml = ${JSON.stringify(html)};\n`,
  );
}

if (!existsSync(RENDERER)) {
  // Vercel builds from a repo checkout, so this should never happen — but if
  // the site is ever built from a partial copy, say so plainly instead of
  // failing with a stack trace about a missing file.
  console.warn(`[compat] ${RENDERER} not found; /compat will show a placeholder`);
  emit(PLACEHOLDER);
  process.exit(0);
}

try {
  const log = execFileSync(process.execPath, [RENDERER, `--out=${SCRATCH}`], {
    cwd: REPO_ROOT,
    encoding: "utf8",
  });
  emit(readFileSync(SCRATCH, "utf8"));
  rmSync(dirname(SCRATCH), { recursive: true, force: true });
  process.stdout.write(`[compat] ${log.trim()}\n`);
} catch (error) {
  console.warn(`[compat] render failed, /compat will show a placeholder: ${error.message}`);
  emit(PLACEHOLDER);
}
