import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { siteUrl } from "@/lib/site-url";

/* The agent pack, assembled at build time from the ONE place it is written:
   /skills/evestack. Same idiom as lib/code-samples.ts — read the real shipped
   files, so the page can never drift from them and a moved file fails the
   build loudly instead of shipping a 404 or, worse, a stale copy.

   This matters more here than for a code sample. The pack is quoted back at
   users as fact by their own agent, and the failure this repository keeps
   paying for is a claim that was true once and is re-stated somewhere nobody
   thinks to update. So there is no second copy of these words anywhere: the
   landing page button, /agent.md, and `npx evestack skills` all resolve to
   these bytes. */

const repoRoot = path.join(process.cwd(), "..", "..");
const packDir = path.join(repoRoot, "skills", "evestack");

/** Frontmatter is eve's routing metadata, not prose — it is lifted into the
    preamble rather than pasted into a chat window as raw YAML. */
function splitFrontmatter(source: string): { frontmatter: string; body: string } {
  if (!/^---\r?\n/.test(source)) return { frontmatter: "", body: source };
  const lines = source.split(/\r?\n/);
  const closing = lines.findIndex((line, i) => i > 0 && line.trimEnd() === "---");
  if (closing === -1) return { frontmatter: "", body: source };
  return {
    frontmatter: lines.slice(1, closing).join("\n"),
    body: lines.slice(closing + 1).join("\n").replace(/^\r?\n/, ""),
  };
}

async function readReferences(): Promise<{ name: string; body: string }[]> {
  const dir = path.join(packDir, "references");
  const entries = (await readdir(dir)).filter((f) => f.endsWith(".md")).sort();
  return Promise.all(
    entries.map(async (file) => ({
      name: file.replace(/\.md$/, ""),
      body: (await readFile(path.join(dir, file), "utf8")).trim(),
    })),
  );
}

/**
 * The pasteable pack.
 *
 * It opens with an instruction, not with documentation, because the two things
 * a user wants from one paste are different: the agent should be able to *use*
 * this immediately, and it should be able to *keep* it. An agent that can write
 * files turns the paste into a real skill on disk and never needs it again; one
 * that cannot still has the whole thing in context. Leading with prose would
 * get the first behaviour only by accident.
 *
 * The reference files are inlined rather than linked. A local model with no
 * fetch tool is the specific case this exists for — llms.txt already serves
 * everyone who can follow a URL.
 */
export async function buildAgentPack(): Promise<string> {
  const skill = await readFile(path.join(packDir, "SKILL.md"), "utf8");
  const { body } = splitFrontmatter(skill);
  const references = await readReferences();

  const preamble = `<!--
  evestack agent setup pack
  ${siteUrl}/agent.md · https://github.com/SammyTourani/evestack
  Generated from /skills/evestack. Do not edit this file; edit the pack.
-->

# Setting you up for evestack

You have been given the evestack skill pack. Everything below is what you need to
help someone install, run, extend and debug evestack.

**If you can write files, save this as a skill so it survives this conversation.**
Write the section marked \`SKILL.md\` to whichever of these your host uses, creating
the directory if needed:

    .claude/skills/evestack/SKILL.md      Claude Code
    agent/skills/evestack/SKILL.md        an eve or evestack agent
    .cursor/rules/evestack.md             Cursor
    AGENTS.md                             append, if you have no skills directory

Write each \`references/*.md\` section to that same directory, keeping the
\`references/\` prefix. Then tell the user where you put it, in one line.

If you cannot write files, just keep reading — everything is inlined below and
nothing here needs to be fetched.

Once you have it: confirm in one sentence that you know what evestack is, and ask
what they want to do. Do not summarise the pack back at them.

---
`;

  const referenceSections = references
    .map(
      ({ name, body: text }) => `
---

## \`references/${name}.md\`

${text}
`,
    )
    .join("\n");

  return `${preamble}
## \`SKILL.md\`

${body.trim()}
${referenceSections}
---

*Source: <${siteUrl}/agent.md> · full documentation: <${siteUrl}/llms-full.txt>*
`;
}

/** Bytes, for the UI to state what it is about to put on someone's clipboard. */
export async function agentPackSize(): Promise<number> {
  return Buffer.byteLength(await buildAgentPack(), "utf8");
}

export interface PackFile {
  /** Slash-separated, relative to the skill root. */
  path: string;
  content: string;
}

/**
 * The pack as a FILE TREE rather than one document.
 *
 * `npx evestack skills` needs this shape, not the pasteable one. A skill is a
 * directory — `SKILL.md` beside `references/*.md` — and that structure is the
 * whole mechanism: the description routes, and the references stay out of
 * context until the model asks for one. Writing the concatenated document to
 * disk as a single file would install something that is no longer a skill, just
 * a large file that happens to be in a skills directory.
 *
 * Frontmatter is preserved here, unlike in the pasteable build, because on disk
 * it is exactly what eve and Claude Code parse.
 */
export async function agentPackFiles(): Promise<PackFile[]> {
  const skill = await readFile(path.join(packDir, "SKILL.md"), "utf8");
  const references = await readReferences();
  return [
    { path: "SKILL.md", content: skill },
    ...references.map(({ name, body }) => ({
      path: `references/${name}.md`,
      content: `${body}\n`,
    })),
  ];
}
