/**
 * A committed floor on how much the suite asserts.
 *
 * Every other guard in this repo answers "did eve change?". This one answers a
 * question nothing else asks: **did the suite quietly get smaller?**
 *
 * It is not hypothetical. Three contracts derive their assertion sets from
 * evestack's own source rather than from a fixed list —
 * `modules/imported-subpaths-resolve` and `modules/imported-values-are-exported`
 * enumerate what the repo actually imports, and
 * `attributes/queried-names-still-emitted` enumerates the `$eve.*` names the
 * dashboard actually reads. Delete an import, or drop a column from a SQL query,
 * and the matching assertion stops being generated. The contract still passes.
 * The suite is simply smaller, and every downstream artifact reports the new
 * number as though it were the old one:
 *
 *   "All 15 contracts hold against eve 0.31.0 — 219 assertions, all green"
 *
 * That sentence is true, and it is the most misleading thing this project could
 * publish: a compatibility page whose coverage silently eroded, certifying a
 * release against assertions that no longer exist. Nothing in the suite, the
 * docs generator, the compat renderer or CI would have noticed.
 *
 * So: a per-contract floor, checked on every run. Per-contract rather than a
 * single total, because a total can hide erosion behind growth — twelve
 * assertions lost from the telemetry contract and twelve gained elsewhere nets
 * to zero and is exactly the case worth catching.
 *
 * Raising the floor is intentional and easy (`--write-floor`). Lowering it is a
 * decision someone has to make on purpose, in a diff, with a reason.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REPO_ROOT } from "./repo.mjs";

export const FLOOR_FILE = join(REPO_ROOT, "contract", "floor.json");

/** Exit code for a floor violation. Distinct from 1 (a contract failed) and 2
 *  (the runner could not start), because it means something categorically
 *  different: the suite did not shrink because eve moved, it shrank because
 *  evestack did. */
export const FLOOR_EXIT_CODE = 3;

export function readFloor() {
  if (!existsSync(FLOOR_FILE)) return null;
  try {
    return JSON.parse(readFileSync(FLOOR_FILE, "utf8"));
  } catch (error) {
    throw new Error(`contract/floor.json is not valid JSON: ${error.message}`);
  }
}

export function writeFloor(report) {
  const floor = {
    $comment:
      "Generated by `node contract/run.mjs --write-floor`. A per-contract minimum " +
      "assertion count. The suite may grow past these numbers freely; dropping below " +
      "one fails the run. See contract/lib/floor.mjs for why.",
    contracts: Object.fromEntries(
      report.contracts
        .filter((c) => c.status !== "skip")
        .map((c) => [c.id, c.assertions.length])
        .sort(([a], [b]) => a.localeCompare(b)),
    ),
  };
  writeFileSync(FLOOR_FILE, `${JSON.stringify(floor, null, 2)}\n`);
  return floor;
}

/**
 * Returns a list of human-readable violations, empty when the report clears the
 * floor.
 *
 * Skipped contracts are exempt but must still be PRESENT: a back-certification
 * run legitimately does not execute the repo-scoped contract, but a contract
 * that vanished from the directory entirely is erosion and must be caught in
 * either mode.
 */
export function checkFloor(report, floor) {
  if (floor === null) return [];
  const violations = [];
  const byId = new Map(report.contracts.map((c) => [c.id, c]));

  for (const [id, minimum] of Object.entries(floor.contracts ?? {})) {
    const contract = byId.get(id);
    if (contract === undefined) {
      violations.push(`${id} is in the floor but did not run at all — was the contract file deleted?`);
      continue;
    }
    // A skipped contract asserts nothing by design; holding it to a count would
    // make every back-certification run fail.
    if (contract.status === "skip") continue;
    if (contract.assertions.length < minimum) {
      violations.push(
        `${id} asserted ${contract.assertions.length}, floor is ${minimum} — ` +
          `${minimum - contract.assertions.length} assertion(s) stopped being generated`,
      );
    }
  }
  return violations;
}
