/**
 * A committed floor on how much the suite asserts.
 *
 * Every other guard in this repo answers "did eve change?". This one answers a
 * question nothing else asks: **did the suite quietly get smaller?**
 *
 * It is not hypothetical. Three contracts derive their assertion sets from
 * evestack's own source rather than from a fixed list —
 * `modules/imported-subpaths-resolve` and `modules/imported-values-are-exported`
 * enumerate what the repo actually imports, and
 * `attributes/queried-names-still-emitted` enumerates the `$eve.*` names the
 * dashboard actually reads. Delete an import, or drop a column from a SQL query,
 * and the matching assertion stops being generated. The contract still passes.
 * The suite is simply smaller, and every downstream artifact reports the new
 * number as though it were the old one:
 *
 *   "All 15 contracts hold against eve 0.31.0 — 219 assertions, all green"
 *
 * That sentence is true, and it is the most misleading thing this project could
 * publish: a compatibility page whose coverage silently eroded, certifying a
 * release against assertions that no longer exist. Nothing in the suite, the
 * docs generator, the compat renderer or CI would have noticed.
 *
 * So: a per-contract floor, checked on every run. Per-contract rather than a
 * single total, because a total can hide erosion behind growth — twelve
 * assertions lost from the telemetry contract and twelve gained elsewhere nets
 * to zero and is exactly the case worth catching.
 *
 * Raising the floor is intentional and easy (`--write-floor`). Lowering it is a
 * decision someone has to make on purpose, in a diff, with a reason.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { REPO_ROOT } from "./repo.mjs";

export const FLOOR_FILE = join(REPO_ROOT, "contract", "floor.json");

/** Exit code for a floor violation. Distinct from 1 (a contract failed) and 2
 *  (the runner could not start), because it means something categorically
 *  different: the suite did not shrink because eve moved, it shrank because
 *  evestack did.
 *
 *  It is also the junior of the two non-zero verdicts. A run that both fails a
 *  contract and shrinks exits 1: coverage that stopped being written can wait, an
 *  assumption that no longer holds about the eve installed right now cannot. run.mjs
 *  prints both findings and gives the code to the failure.
 *
 *  Which is why run.mjs only reaches for it when the suite is describing the
 *  install this checkout owns. Pointed at some other release, a lower count is
 *  eve having less surface, and saying "evestack did" would be a false accusation
 *  on every release older than the pin. */
export const FLOOR_EXIT_CODE = 3;

export function readFloor() {
  if (!existsSync(FLOOR_FILE)) return null;
  try {
    return JSON.parse(readFileSync(FLOOR_FILE, "utf8"));
  } catch (error) {
    throw new Error(`contract/floor.json is not valid JSON: ${error.message}`);
  }
}

export function writeFloor(report) {
  const floor = {
    $comment:
      "Generated by `node contract/run.mjs --write-floor`. A per-contract minimum " +
      "assertion count. The suite may grow past these numbers freely; dropping below " +
      "one fails the run. See contract/lib/floor.mjs for why.",
    contracts: Object.fromEntries(
      report.contracts
        .filter((c) => c.status !== "skip")
        .map((c) => [c.id, c.assertions.length])
        .sort(([a], [b]) => a.localeCompare(b)),
    ),
  };
  writeFileSync(FLOOR_FILE, `${JSON.stringify(floor, null, 2)}\n`);
  return floor;
}

/**
 * Every contract that ran and asserted fewer times than the floor records —
 * structured, and deliberately not worded.
 *
 * The wording cannot live here, because the same shortfall means two different
 * things depending on which eve is being interrogated. Against the install this
 * checkout owns it means evestack eroded. Against a release supplied by
 * EVESTACK_CONTRACT_EVE_DIR it usually means that release does not carry a surface
 * the pinned one has: `action.partial` did not exist before eve 0.30.8, so the
 * contract that reconciles it generates one assertion instead of two on every
 * earlier release. Calling that "the suite shrank" sends a maintainer hunting for
 * a deleted import that was never deleted. run.mjs picks the sentence.
 *
 * Skipped contracts are exempt but must still be PRESENT: a back-certification run
 * legitimately does not execute the repo-scoped contracts, but a contract that
 * vanished from the directory entirely is erosion and must be caught in either mode.
 */
export function floorShortfalls(report, floor) {
  if (floor === null) return [];
  const shortfalls = [];
  const byId = new Map(report.contracts.map((c) => [c.id, c]));

  for (const [id, minimum] of Object.entries(floor.contracts ?? {})) {
    const contract = byId.get(id);
    if (contract === undefined) {
      shortfalls.push({ id, minimum, asserted: null, absent: true });
      continue;
    }
    // A skipped contract asserts nothing by design; holding it to a count would
    // make every back-certification run fail.
    if (contract.status === "skip") continue;
    if (contract.assertions.length < minimum) {
      shortfalls.push({ id, minimum, asserted: contract.assertions.length, absent: false });
    }
  }
  return shortfalls;
}

/**
 * The erosion wording. Correct only when the suite is describing its own install;
 * run.mjs uses the structured form above when it is not.
 */
export function describeShortfall(s) {
  return s.absent
    ? `${s.id} is in the floor but did not run at all — was the contract file deleted?`
    : `${s.id} asserted ${s.asserted}, floor is ${s.minimum} — ` +
      `${s.minimum - s.asserted} assertion(s) stopped being generated`;
}
