import { UNCONFIGURED_MESSAGE, authConfigured, safeNextPath } from "@/lib/auth";

export const dynamic = "force-dynamic";

/**
 * The only page reachable without a session.
 *
 * A plain `<form method="post">` with no client component behind it, on
 * purpose: the one page that has to work when everything else is refused should
 * not depend on a JavaScript bundle having loaded. It posts to
 * /api/auth/session, which is the only route that reads the password.
 */

const ERRORS: Record<string, string> = {
  invalid: "That user and password were not accepted.",
  missing: "Both fields are required.",
  unconfigured: UNCONFIGURED_MESSAGE,
};

function first(value: string | string[] | undefined): string {
  if (Array.isArray(value)) return value[0] ?? "";
  return value ?? "";
}

export default async function SignInPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>;
}) {
  const params = await searchParams;
  const next = safeNextPath(first(params.next));
  const failure = first(params.error);
  const configured = authConfigured();

  return (
    <div className="signin">
      <h1>Sign in</h1>
      <p className="page-sub">
        This dashboard can start agent runs, approve tool calls and delete memories, so it asks
        who you are first.
      </p>

      {!configured ? (
        <p className="signin-error" role="alert">
          {UNCONFIGURED_MESSAGE}
        </p>
      ) : (
        <form className="signin-form" method="post" action="/api/auth/session">
          <input type="hidden" name="next" value={next} />

          {failure ? (
            <p className="signin-error" role="alert">
              {ERRORS[failure] ?? "Sign-in failed."}
            </p>
          ) : null}

          <label className="signin-field">
            <span>User</span>
            <input name="user" type="text" autoComplete="username" defaultValue="" autoFocus required />
          </label>

          <label className="signin-field">
            <span>Password</span>
            <input name="password" type="password" autoComplete="current-password" required />
          </label>

          <button className="signin-submit" type="submit">
            Sign in
          </button>
        </form>
      )}

      <p className="signin-hint">
        The credentials are <code>EVESTACK_AUTH_USER</code> and <code>EVESTACK_AUTH_PASSWORD</code>
        {" "}— the same pair the agent uses, generated by <code>create-evestack</code>. Scripts can
        skip this page and send them as HTTP Basic instead.
      </p>
    </div>
  );
}
