/**
 * Token pricing, in USD per million tokens.
 *
 * We compute cost ourselves because nothing upstream can tell us. eve only
 * attaches `gen_ai.usage.cost` to spans when the call was served by Vercel's AI
 * Gateway; a self-hosted agent calls its provider directly, so that attribute
 * is simply absent. Token *counts* are always present, so price × tokens is the
 * only path to a cost figure.
 *
 * The table below used to be seven models typed by hand under a comment saying
 * they go stale. They had: measured against Vercel's catalog on 2026-08-05, this
 * file billed anthropic/claude-opus-4.8 at 15/75 against a real 5/25 and
 * claude-sonnet-5 at 3/15 against a real 2/10. Both errors overstate spend, and
 * claude-sonnet-5 is what templates/default picks when EVESTACK_PROVIDER is
 * anthropic — so the default configuration was the wrong one. The table is now
 * generated from https://ai-gateway.vercel.sh/v1/models, the same catalog eve
 * consults for a model's context window, and committed. See
 * scripts/gen-pricing.mjs for what is included and why, and for the region and
 * regional-pricing decisions in particular.
 *
 * Nothing here fetches anything. The generator is a script someone runs; this
 * module is a lookup over literals, because the promise of this project is that
 * a self-hosted install phones nobody.
 *
 * Prices still move, and a regenerated table is only as fresh as the last run of
 * the script. Override a single model without touching this file, and without
 * waiting for anyone:
 *
 *   EVESTACK_PRICING='{"openai/gpt-5-mini":{"input":0.25,"output":2,"cacheRead":0.025}}'
 *
 * Unknown models cost 0 and are surfaced in the UI as "unpriced" rather than
 * silently counted as free — an unpriced model must never look cheap.
 */
export interface ModelPrice {
  /** USD per 1M input tokens. */
  input: number;
  /** USD per 1M output tokens. */
  output: number;
  /** USD per 1M cached input tokens; defaults to 10% of input when omitted. */
  cacheRead?: number;
  /**
   * USD per 1M tokens written to the prompt cache; defaults to the plain input
   * rate when omitted, never to zero. See `costUsd` for why that floor and not
   * the 1.25x premium most of the stated rates carry.
   *
   * 33 of the 206 priced models state one, and every one of those also states a
   * cache-read rate.
   */
  cacheWrite?: number;
}

/**
 * The floor under the generated table, for the case where the generated region
 * is empty or was never filled in.
 *
 * Kept deliberately tiny. Every number here is one somebody has to notice has
 * gone stale, which is the failure this whole file is a fix for, so this is only
 * the two paid models `templates/default/agent/agent.ts` reaches for by default
 * — plus the local wildcard, which no catalog will ever carry.
 *
 * Anything the generated table also knows about is shadowed by it, so on a
 * normal checkout these entries are never read.
 */
const FALLBACK_PRICING: Record<string, ModelPrice> = {
  "openai/gpt-5-mini": { input: 0.25, output: 2, cacheRead: 0.025 },
  "anthropic/claude-sonnet-5": { input: 2, output: 10, cacheRead: 0.2 },
  // Local models are free by definition — that is the point of the Ollama path.
  // The gateway catalog contains no `ollama/` entry at all (checked: zero of
  // 317), so this rule cannot come from the generator.
  "ollama/*": { input: 0, output: 0, cacheRead: 0 },
};

// GENERATED:pricing start
// Generated by scripts/gen-pricing.mjs from https://ai-gateway.vercel.sh/v1/models.
// Do not edit inside these markers; run the script instead. USD per 1M tokens.
// 206 models. sha256:6bbdc839af4a061f
const GATEWAY_PRICING: Record<string, ModelPrice> = {
  "alibaba/qwen-3-14b": { input: 0.12, output: 0.24 },
  "alibaba/qwen-3-235b": { input: 0.22, output: 0.88 },
  "alibaba/qwen-3-30b": { input: 0.12, output: 0.5 },
  "alibaba/qwen-3-32b": { input: 0.16, output: 0.64 },
  "alibaba/qwen-3.6-max-preview": { input: 1.3, output: 7.8, cacheRead: 0.26, cacheWrite: 1.625 },
  "alibaba/qwen3-235b-a22b-thinking": { input: 0.4, output: 4 },
  "alibaba/qwen3-coder": { input: 1.5, output: 7.5, cacheRead: 0.3 },
  "alibaba/qwen3-coder-30b-a3b": { input: 0.15, output: 0.6 },
  "alibaba/qwen3-coder-next": { input: 0.5, output: 1.2 },
  "alibaba/qwen3-coder-plus": { input: 1, output: 5, cacheRead: 0.2 },
  "alibaba/qwen3-max": { input: 1.2, output: 6, cacheRead: 0.24 },
  "alibaba/qwen3-max-preview": { input: 1.2, output: 6, cacheRead: 0.24 },
  "alibaba/qwen3-max-thinking": { input: 1.2, output: 6, cacheRead: 0.24 },
  "alibaba/qwen3-next-80b-a3b-instruct": { input: 0.15, output: 1.2 },
  "alibaba/qwen3-next-80b-a3b-thinking": { input: 0.15, output: 1.2 },
  "alibaba/qwen3-vl-235b-a22b-instruct": { input: 0.4, output: 1.6 },
  "alibaba/qwen3-vl-instruct": { input: 0.4, output: 1.6 },
  "alibaba/qwen3-vl-thinking": { input: 0.4, output: 4 },
  "alibaba/qwen3.5-flash": { input: 0.1, output: 0.4, cacheRead: 0.001, cacheWrite: 0.125 },
  "alibaba/qwen3.5-plus": { input: 0.4, output: 2.4, cacheRead: 0.04, cacheWrite: 0.5 },
  "alibaba/qwen3.6-27b": { input: 0.6, output: 3.6 },
  "alibaba/qwen3.6-plus": { input: 0.5, output: 3, cacheRead: 0.1, cacheWrite: 0.625 },
  "alibaba/qwen3.7-flash": { input: 0.03, output: 0.13, cacheRead: 0.006, cacheWrite: 0.038 },
  "alibaba/qwen3.7-max": { input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.125 },
  "alibaba/qwen3.7-plus": { input: 0.4, output: 1.6, cacheRead: 0.08, cacheWrite: 0.5 },
  "alibaba/qwen3.8-max": { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 2.5 },
  "amazon/nova-2-lite": { input: 0.3, output: 2.5, cacheRead: 0.075 },
  "amazon/nova-lite": { input: 0.06, output: 0.24 },
  "amazon/nova-micro": { input: 0.035, output: 0.14 },
  "amazon/nova-pro": { input: 0.8, output: 3.2 },
  "anthropic/claude-3-haiku": { input: 0.25, output: 1.25, cacheRead: 0.03, cacheWrite: 0.3 },
  "anthropic/claude-fable-5": { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
  "anthropic/claude-haiku-4.5": { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
  "anthropic/claude-opus-4": { input: 15, output: 75, cacheRead: 1.5, cacheWrite: 18.75 },
  "anthropic/claude-opus-4.5": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "anthropic/claude-opus-4.6": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "anthropic/claude-opus-4.7": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "anthropic/claude-opus-4.8": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "anthropic/claude-opus-4.8-fast": { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
  "anthropic/claude-opus-5": { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
  "anthropic/claude-opus-5-fast": { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
  "anthropic/claude-sonnet-4": { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
  "anthropic/claude-sonnet-4.5": { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
  "anthropic/claude-sonnet-4.6": { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
  "anthropic/claude-sonnet-5": { input: 2, output: 10, cacheRead: 0.2, cacheWrite: 2.5 },
  "arcee-ai/trinity-large-thinking": { input: 0.25, output: 0.9 },
  "arcee-ai/trinity-mini": { input: 0.045, output: 0.15 },
  "bytedance/seed-1.6": { input: 0.25, output: 2, cacheRead: 0.05 },
  "bytedance/seed-1.8": { input: 0.25, output: 2, cacheRead: 0.05 },
  "cohere/command-a": { input: 2.5, output: 10 },
  "deepseek/deepseek-r1": { input: 1.35, output: 5.4 },
  "deepseek/deepseek-v3": { input: 0.27, output: 1.12, cacheRead: 0.135 },
  "deepseek/deepseek-v3.1": { input: 0.25, output: 0.95, cacheRead: 0.13 },
  "deepseek/deepseek-v3.1-terminus": { input: 0.27, output: 1, cacheRead: 0.135 },
  "deepseek/deepseek-v3.2": { input: 0.28, output: 0.42, cacheRead: 0.028 },
  "deepseek/deepseek-v3.2-thinking": { input: 0.62, output: 1.85 },
  "deepseek/deepseek-v4-flash": { input: 0.2, output: 0.4, cacheRead: 0.04 },
  "deepseek/deepseek-v4-flash-0731": { input: 0.13, output: 0.26, cacheRead: 0.028 },
  "deepseek/deepseek-v4-pro": { input: 1.74, output: 3.48, cacheRead: 0.14 },
  "google/gemini-2.5-flash": { input: 0.3, output: 2.5, cacheRead: 0.03 },
  "google/gemini-2.5-flash-image": { input: 0.3, output: 2.5, cacheRead: 0.03 },
  "google/gemini-2.5-flash-lite": { input: 0.1, output: 0.4, cacheRead: 0.01 },
  "google/gemini-2.5-pro": { input: 1.25, output: 10, cacheRead: 0.125 },
  "google/gemini-3-flash": { input: 0.5, output: 3, cacheRead: 0.05 },
  "google/gemini-3-pro-image": { input: 2, output: 12, cacheRead: 0.2 },
  "google/gemini-3.1-flash-image": { input: 0.5, output: 3, cacheRead: 0.05 },
  "google/gemini-3.1-flash-image-preview": { input: 0.5, output: 3, cacheRead: 0.05 },
  "google/gemini-3.1-flash-lite": { input: 0.25, output: 1.5, cacheRead: 0.03 },
  "google/gemini-3.1-flash-lite-image": { input: 0.25, output: 1.5, cacheRead: 0.03 },
  "google/gemini-3.1-pro-preview": { input: 2, output: 12, cacheRead: 0.2 },
  "google/gemini-3.5-flash": { input: 1.5, output: 9, cacheRead: 0.15 },
  "google/gemini-3.5-flash-lite": { input: 0.3, output: 2.5, cacheRead: 0.03 },
  "google/gemini-3.6-flash": { input: 1.5, output: 7.5, cacheRead: 0.15 },
  "google/gemini-omni-flash-preview": { input: 1.5, output: 9 },
  "google/gemma-4-26b-a4b-it": { input: 0.15, output: 0.6, cacheRead: 0.015 },
  "google/gemma-4-31b-it": { input: 0.14, output: 0.4 },
  "inception/mercury-2": { input: 0.25, output: 0.75, cacheRead: 0.025 },
  "inception/mercury-coder-small": { input: 0.25, output: 1 },
  "inclusionai/ling-3.0-flash-free": { input: 0, output: 0 },
  "interfaze/interfaze-beta": { input: 1.5, output: 3.5 },
  "kwaipilot/kat-coder-air-v2.5": { input: 0.15, output: 0.6, cacheRead: 0.03 },
  "kwaipilot/kat-coder-pro-v1": { input: 0.3, output: 1.2, cacheRead: 0.06 },
  "kwaipilot/kat-coder-pro-v2": { input: 0.3, output: 1.2, cacheRead: 0.06 },
  "kwaipilot/kat-coder-pro-v2.5": { input: 0.74, output: 2.96, cacheRead: 0.15 },
  "meta/llama-3.1-70b": { input: 0.72, output: 0.72 },
  "meta/llama-3.1-8b": { input: 0.22, output: 0.22 },
  "meta/llama-3.3-70b": { input: 0.72, output: 0.72 },
  "meta/llama-4-maverick": { input: 0.24, output: 0.97 },
  "meta/llama-4-scout": { input: 0.17, output: 0.66 },
  "meta/muse-spark-1.1": { input: 1.25, output: 4.25, cacheRead: 0.15 },
  "meta/muse-spark-1.2": { input: 1.25, output: 4.25, cacheRead: 0.15 },
  "meta/muse-spark-1.2-contributor": { input: 0.1, output: 0.2, cacheRead: 0.002 },
  "minimax/minimax-m2": { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0.375 },
  "minimax/minimax-m2.1": { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0.375 },
  "minimax/minimax-m2.1-lightning": { input: 0.3, output: 2.4, cacheRead: 0.03, cacheWrite: 0.375 },
  "minimax/minimax-m2.5": { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0.375 },
  "minimax/minimax-m2.5-highspeed": { input: 0.6, output: 2.4, cacheRead: 0.03, cacheWrite: 0.375 },
  "minimax/minimax-m2.7": { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0.375 },
  "minimax/minimax-m2.7-highspeed": { input: 0.6, output: 2.4, cacheRead: 0.06, cacheWrite: 0.375 },
  "minimax/minimax-m3": { input: 0.3, output: 1.2, cacheRead: 0.06 },
  "mistral/codestral": { input: 0.3, output: 0.9 },
  "mistral/devstral-2": { input: 0.4, output: 2 },
  "mistral/devstral-small-2": { input: 0.1, output: 0.3 },
  "mistral/magistral-medium": { input: 2, output: 5 },
  "mistral/magistral-small": { input: 0.5, output: 1.5 },
  "mistral/ministral-14b": { input: 0.2, output: 0.2 },
  "mistral/ministral-3b": { input: 0.1, output: 0.1 },
  "mistral/ministral-8b": { input: 0.15, output: 0.15 },
  "mistral/mistral-large-3": { input: 0.5, output: 1.5 },
  "mistral/mistral-medium": { input: 0.4, output: 2 },
  "mistral/mistral-medium-3.5": { input: 1.5, output: 7.5 },
  "mistral/mistral-nemo": { input: 0.15, output: 0.15 },
  "mistral/mistral-small": { input: 0.1, output: 0.3 },
  "mistral/pixtral-12b": { input: 0.15, output: 0.15 },
  "moonshotai/kimi-k2": { input: 0.57, output: 2.3 },
  "moonshotai/kimi-k2-thinking": { input: 0.47, output: 2, cacheRead: 0.141 },
  "moonshotai/kimi-k2.5": { input: 0.6, output: 3, cacheRead: 0.1 },
  "moonshotai/kimi-k2.6": { input: 0.95, output: 4, cacheRead: 0.16 },
  "moonshotai/kimi-k2.7-code": { input: 0.95, output: 4, cacheRead: 0.19 },
  "moonshotai/kimi-k2.7-code-highspeed": { input: 1.9, output: 8, cacheRead: 0.38 },
  "moonshotai/kimi-k3": { input: 3, output: 15, cacheRead: 0.3 },
  "moonshotai/kimi-k3-fast": { input: 4.5, output: 22.5, cacheRead: 0.45 },
  "morph/morph-v3-fast": { input: 0.8, output: 1.2 },
  "morph/morph-v3-large": { input: 0.9, output: 1.9 },
  "nvidia/nemotron-3-nano-30b-a3b": { input: 0.05, output: 0.24 },
  "nvidia/nemotron-3-super-120b-a12b": { input: 0.15, output: 0.65 },
  "nvidia/nemotron-3-ultra-550b-a55b": { input: 0.6, output: 2.4, cacheRead: 0.12 },
  "nvidia/nemotron-nano-12b-v2-vl": { input: 0.2, output: 0.6 },
  "nvidia/nemotron-nano-9b-v2": { input: 0.06, output: 0.23 },
  "openai/gpt-3.5-turbo": { input: 0.5, output: 1.5 },
  "openai/gpt-4-turbo": { input: 10, output: 30 },
  "openai/gpt-4.1": { input: 2, output: 8, cacheRead: 0.5 },
  "openai/gpt-4.1-mini": { input: 0.4, output: 1.6, cacheRead: 0.1 },
  "openai/gpt-4.1-nano": { input: 0.1, output: 0.4, cacheRead: 0.025 },
  "openai/gpt-4o": { input: 2.5, output: 10, cacheRead: 1.25 },
  "openai/gpt-4o-mini": { input: 0.15, output: 0.6, cacheRead: 0.075 },
  "openai/gpt-4o-mini-search-preview": { input: 0.15, output: 0.6 },
  "openai/gpt-5": { input: 1.25, output: 10, cacheRead: 0.125 },
  "openai/gpt-5-codex": { input: 1.25, output: 10, cacheRead: 0.13 },
  "openai/gpt-5-mini": { input: 0.25, output: 2, cacheRead: 0.025 },
  "openai/gpt-5-nano": { input: 0.05, output: 0.4, cacheRead: 0.005 },
  "openai/gpt-5-pro": { input: 15, output: 120 },
  "openai/gpt-5.1-codex": { input: 1.25, output: 10, cacheRead: 0.13 },
  "openai/gpt-5.1-codex-max": { input: 1.25, output: 10, cacheRead: 0.125 },
  "openai/gpt-5.1-codex-mini": { input: 0.25, output: 2, cacheRead: 0.03 },
  "openai/gpt-5.1-instant": { input: 1.25, output: 10, cacheRead: 0.13 },
  "openai/gpt-5.1-thinking": { input: 1.25, output: 10, cacheRead: 0.125 },
  "openai/gpt-5.2": { input: 1.75, output: 14, cacheRead: 0.175 },
  "openai/gpt-5.2-codex": { input: 1.75, output: 14, cacheRead: 0.175 },
  "openai/gpt-5.2-pro": { input: 21, output: 168 },
  "openai/gpt-5.3-chat": { input: 1.75, output: 14, cacheRead: 0.175 },
  "openai/gpt-5.3-codex": { input: 1.75, output: 14, cacheRead: 0.175 },
  "openai/gpt-5.4": { input: 2.5, output: 15, cacheRead: 0.25 },
  "openai/gpt-5.4-mini": { input: 0.75, output: 4.5, cacheRead: 0.075 },
  "openai/gpt-5.4-nano": { input: 0.2, output: 1.25, cacheRead: 0.02 },
  "openai/gpt-5.4-pro": { input: 30, output: 180 },
  "openai/gpt-5.5": { input: 5, output: 30, cacheRead: 0.5 },
  "openai/gpt-5.5-pro": { input: 30, output: 180 },
  "openai/gpt-5.6-luna": { input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25 },
  "openai/gpt-5.6-sol": { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
  "openai/gpt-5.6-terra": { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 2.5 },
  "openai/gpt-oss-120b": { input: 0.1, output: 0.5 },
  "openai/gpt-oss-20b": { input: 0.05, output: 0.2 },
  "openai/gpt-oss-safeguard-20b": { input: 0.075, output: 0.3, cacheRead: 0.037 },
  "openai/o1": { input: 15, output: 60, cacheRead: 7.5 },
  "openai/o3": { input: 2, output: 8, cacheRead: 0.5 },
  "openai/o3-deep-research": { input: 10, output: 40, cacheRead: 2.5 },
  "openai/o3-mini": { input: 1.1, output: 4.4, cacheRead: 0.55 },
  "openai/o3-pro": { input: 20, output: 80 },
  "openai/o4-mini": { input: 1.1, output: 4.4, cacheRead: 0.275 },
  "poolside/laguna-s-2.1": { input: 0.1, output: 0.2, cacheRead: 0.01 },
  "poolside/laguna-s-2.1-free": { input: 0, output: 0 },
  "sakana/fugu-ultra": { input: 5, output: 30, cacheRead: 0.5 },
  "stepfun/step-3.5-flash": { input: 0.09, output: 0.3, cacheRead: 0.02 },
  "stepfun/step-3.7-flash": { input: 0.2, output: 1.15, cacheRead: 0.04 },
  "tencent/hy3": { input: 0.14, output: 0.58, cacheRead: 0.035 },
  "thinkingmachines/inkling": { input: 1, output: 4.05, cacheRead: 0.17 },
  "thinkingmachines/inkling-small": { input: 0.5, output: 1.2, cacheRead: 0.1 },
  "xai/grok-4.1-fast-non-reasoning": { input: 0.2, output: 0.5, cacheRead: 0.05 },
  "xai/grok-4.1-fast-reasoning": { input: 0.2, output: 0.5, cacheRead: 0.05 },
  "xai/grok-4.20-multi-agent": { input: 1.25, output: 2.5, cacheRead: 0.2 },
  "xai/grok-4.20-multi-agent-beta": { input: 1.25, output: 2.5, cacheRead: 0.2 },
  "xai/grok-4.20-non-reasoning": { input: 1.25, output: 2.5, cacheRead: 0.2 },
  "xai/grok-4.20-non-reasoning-beta": { input: 1.25, output: 2.5, cacheRead: 0.2 },
  "xai/grok-4.20-reasoning": { input: 1.25, output: 2.5, cacheRead: 0.2 },
  "xai/grok-4.20-reasoning-beta": { input: 1.25, output: 2.5, cacheRead: 0.2 },
  "xai/grok-4.3": { input: 1.25, output: 2.5, cacheRead: 0.2 },
  "xai/grok-4.5": { input: 2, output: 6, cacheRead: 0.3 },
  "xai/grok-build-0.1": { input: 1, output: 2, cacheRead: 0.2 },
  "xiaomi/mimo-v2.5": { input: 0.14, output: 0.28, cacheRead: 0.0028 },
  "xiaomi/mimo-v2.5-pro": { input: 0.435, output: 0.87, cacheRead: 0.0036 },
  "zai/glm-4.5": { input: 0.6, output: 2.2, cacheRead: 0.11 },
  "zai/glm-4.5-air": { input: 0.2, output: 1.1, cacheRead: 0.03 },
  "zai/glm-4.5v": { input: 0.6, output: 1.8, cacheRead: 0.11 },
  "zai/glm-4.6": { input: 0.6, output: 2.2, cacheRead: 0.11 },
  "zai/glm-4.6v": { input: 0.3, output: 0.9, cacheRead: 0.05 },
  "zai/glm-4.6v-flash": { input: 0, output: 0 },
  "zai/glm-4.7": { input: 0.6, output: 2.2, cacheRead: 0.12 },
  "zai/glm-4.7-flash": { input: 0.07, output: 0.4 },
  "zai/glm-4.7-flashx": { input: 0.06, output: 0.4, cacheRead: 0.01 },
  "zai/glm-5": { input: 1, output: 3.2 },
  "zai/glm-5-turbo": { input: 1.2, output: 4, cacheRead: 0.24 },
  "zai/glm-5.1": { input: 1.4, output: 4.4, cacheRead: 0.26 },
  "zai/glm-5.2": { input: 1.1, output: 3.851, cacheRead: 0.275 },
  "zai/glm-5.2-fast": { input: 2.1, output: 6.6, cacheRead: 0.21 },
  "zai/glm-5v-turbo": { input: 1.2, output: 4, cacheRead: 0.24 },
};
// GENERATED:pricing end

/**
 * The merged table, built once.
 *
 * This used to re-spread the defaults on every call, which was free when the
 * table had seven entries. The generated table is two orders of magnitude bigger
 * and `findPrice` runs per turn row, so the spread and the wildcard scan are now
 * done once and the hot path is a plain property lookup.
 */
let table: Record<string, ModelPrice> | null = null;
let wildcards: Array<{ prefix: string; price: ModelPrice }> = [];

function build(): Record<string, ModelPrice> {
  let overrides: Record<string, ModelPrice> = {};
  const raw = process.env.EVESTACK_PRICING;
  if (raw) {
    try {
      overrides = JSON.parse(raw) as Record<string, ModelPrice>;
    } catch {
      console.warn("[evestack] EVESTACK_PRICING is not valid JSON; ignoring it.");
    }
  }

  // Later wins: a generated price beats the hand-written floor, and an operator's
  // override beats both. An operator who has negotiated rates, or is routing
  // through a region the catalog prices higher, is the only party here who knows
  // what they are actually billed.
  const merged = { ...FALLBACK_PRICING, ...GATEWAY_PRICING, ...overrides };

  wildcards = Object.entries(merged)
    .filter(([key]) => key.endsWith("/*"))
    .map(([key, price]) => ({ prefix: key.slice(0, -1), price }));

  table = merged;
  return merged;
}

export function findPrice(model: string | null): ModelPrice | null {
  if (!model) return null;
  const known = table ?? build();
  const exact = known[model];
  if (exact) return exact;
  // Prefix wildcards, so "ollama/*" covers every local model.
  for (const { prefix, price } of wildcards) {
    if (model.startsWith(prefix)) return price;
  }
  return null;
}

export function isPriced(model: string | null): boolean {
  return findPrice(model) !== null;
}

/**
 * The rate a cached read is billed at.
 *
 * The fallback is only reached by models the catalog states no cache read price
 * for — 66 of the 206 it prices. Among the 140 that do state one, the ratio to
 * input runs from 0.008 to 0.52 and 59 sit at exactly 0.10, so this is the
 * plurality rather than a rule, and it is never used to shadow a rate we were
 * told.
 *
 * Shared with `cacheSavingsUsd` on purpose: a saving measured against a rate
 * other than the one we charged is not a saving.
 */
function cacheReadRateOf(price: ModelPrice): number {
  return price.cacheRead ?? price.input * 0.1;
}

/**
 * Every token class at its own rate, the way Datadog's `ml_obs` model splits a
 * span into `input.non_cached`, `input.cache_read` and `input.cache_write`.
 *
 * Cache reads and cache writes both arrive INSIDE the input total, so neither
 * may also be charged at the full input rate. That is not an assumption about
 * eve: `$eve.input_tokens` is the AI SDK's `usage.inputTokens`, and the SDK
 * flattens it from `inputTokens.total`, which @ai-sdk/anthropic builds as
 * `noCache + cacheRead + cacheWrite` (convert-anthropic-usage.ts). Subtracting
 * both is what leaves the non-cached remainder.
 */
export function costUsd(
  model: string | null,
  inputTokens: number,
  outputTokens: number,
  cacheReadTokens = 0,
  cacheWriteTokens = 0,
): number {
  const price = findPrice(model);
  if (!price) return 0;
  // A model the catalog states no cache-write price for is charged the plain
  // input rate. Zero is not an option — these are prompt tokens the provider
  // read and billed, and a class quietly worth nothing is the same lie as an
  // unpriced model rendering $0.00. Neither is assuming the premium: 29 of the
  // 33 stated rates are exactly 1.25x input, but those 33 are precisely the
  // providers who charge extra, and the catalog contradicts the pattern anyway
  // — minimax/minimax-m2.5-highspeed writes at 0.625x input. The input rate is
  // also the number these tokens already produced before this function took a
  // write count, so the 173 silent models do not move.
  const cacheWriteRate = price.cacheWrite ?? price.input;
  const nonCachedTokens = Math.max(0, inputTokens - cacheReadTokens - cacheWriteTokens);
  return (
    (nonCachedTokens / 1_000_000) * price.input +
    (outputTokens / 1_000_000) * price.output +
    (cacheReadTokens / 1_000_000) * cacheReadRateOf(price) +
    (cacheWriteTokens / 1_000_000) * cacheWriteRate
  );
}

/**
 * What the prompt cache saved: the cached tokens billed at the read rate rather
 * than at the input rate they would have cost uncached.
 *
 * Null, not zero, for a model we cannot price, and the return type is the
 * enforcement. `costUsd` can return 0 for an unpriced model because every
 * caller of it already gates on `isPriced()`; this figure has no such
 * convention around it yet, and "saved $0.00" must not read the same as "we
 * have no idea what this cache was worth".
 *
 * Zero IS the right answer for `ollama/*`: nothing was spent, so nothing was
 * saved. That case is priced, so it returns a number, which is the whole
 * distinction null exists to keep.
 */
export function cacheSavingsUsd(model: string | null, cacheReadTokens: number): number | null {
  const price = findPrice(model);
  if (!price) return null;
  // Never negative: no catalog entry prices a cached read above its own input
  // rate (checked: 0 of 140), and the 0.1 fallback cannot either.
  return (Math.max(0, cacheReadTokens) / 1_000_000) * (price.input - cacheReadRateOf(price));
}

export function formatUsd(value: number): string {
  if (value === 0) return "$0.00";
  if (value < 0.01) return `$${value.toFixed(4)}`;
  return `$${value.toFixed(2)}`;
}
